modLoader="lowcodefml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Vazkii/Quark"
license="https://github.com/Vazkii/Quark/blob/master/LICENSE.md"

[[mods]]
modId="quarkoddities"
displayName="Quark Oddities"
version="1.20.1"
authors="Vazkii, WireSegal, MCVinnyq, Sully"
description='''Crazier Small things.'''

[[dependencies.quarkoddities]]
modId="quark"
mandatory=true
versionRange="[0,)"